# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  newcchain:
services:
  ca:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.newcchain.com
      #TLS enable
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org3.newcchain.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/06e429dde003af9bdbf744b018132621ca012a4a8b38a204ea5392c19a3f17b9_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org3.newcchain.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/06e429dde003af9bdbf744b018132621ca012a4a8b38a204ea5392c19a3f17b9_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org3.newcchain.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.newcchain.com
    networks:
      - newcchain

  peer0.org3.newcchain.com:
    container_name: peer0.org3.newcchain.com
    extends:
      file: base/peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org3.newcchain.com
      - CORE_PEER_ADDRESS=peer0.org3.newcchain.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org3.newcchain.com:7051
      - CORE_PEER_LOCALMSPID=Org3MSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=orderer-peer-ca
    volumes:
        - /var/run/:/host/var/run/
        - ./config:/etc/hyperledger/configtx
        - ./crypto-config/peerOrganizations/org3.newcchain.com/peers/peer0.org3.newcchain.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/org3.newcchain.com/peers/peer0.org3.newcchain.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 7051:7051
      - 7053:7053
    depends_on:
      - couchdb0
    networks:
      - newcchain

  peer1.org3.newcchain.com:
    container_name: peer1.org3.newcchain.com
    extends:
      file: base/peer-base.yaml
      service: peer-base
    environment:  
      - CORE_PEER_ADDRESS=peer1.org3.newcchain.com:7051
      - CORE_PEER_LOCALMSPID=Org3MSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=orderer-peer-ca
    volumes:
        - /var/run/:/host/var/run/
        - ./config:/etc/hyperledger/configtx
        - ./crypto-config/peerOrganizations/org3.newcchain.com/peers/peer1.org3.newcchain.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/org3.newcchain.com/peers/peer1.org3.newcchain.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 8051:7051
      - 8053:7053
    depends_on:
      - couchdb1  
    networks:
      - newcchain

  couchdb0:
    container_name: couchdb0
    image: hyperledger/fabric-couchdb
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=orderer-peer-ca
    ports:
      - 5984:5984
    networks:
      - newcchain

  couchdb1:
    container_name: couchdb1
    image: hyperledger/fabric-couchdb
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=orderer-peer-ca
    ports:
      - 5994:5984
    networks:
      - newcchain           

  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=INFO
      #- CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.org3.newcchain.com:7051
      - CORE_PEER_LOCALMSPID=Org3MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org3.newcchain.com/peers/peer0.org3.newcchain.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org3.newcchain.com/peers/peer0.org3.newcchain.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org3.newcchain.com/peers/peer0.org3.newcchain.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org3.newcchain.com/users/Admin@org3.newcchain.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./config/peerOrganizations/org1.newcchain.com:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.newcchain.com
        - ./config/peerOrganizations/org2.newcchain.com:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org2.newcchain.com
        - ./config/peerOrganizations/org3.newcchain.com:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org3.newcchain.com
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
    depends_on:
      - peer0.org3.newcchain.com
      - peer1.org3.newcchain.com
    networks:
      - newcchain

